### ISSUE TITLE
Precision in language varieties

### ISSUE THREAD

**Issue by olgapelloni** [MorphDiv/TeDDi_sample#139]
I have started to write a new crawler from OPUS to gather the technical texts (program manuals and localization files).

It seems that there is no description with ISO codes on OPUS, they mostly use their own ids. Thus, several languages from our sample are not presented there with their precise name.
The cases I encountered so far (OPUS id and name vs. our name):

ar Arabic / Arabic_Egyptian_arz (another varieties are marked on OPUS; Egyptian Arabic is assumed to be standard, so I think they mean Egyptian Arabic here)
ber Berber languages / Berber_MiddleAtlas_tzm
mg Malagasy / Malagasy_plt (Plateau Malagasy)
om Oromo / Oromo_Harar_hae
qu Quechua / Quechua_Imbabura_qvi

It was an issue before when I crawled the OpenSubtitles, and at that point I skipped these languages. However, I guess this issue will occur not only further with the OPUS corpora, but with another web sources as well.

On one hand, it's a pity to skip these languages, especially, since for many of them there are only 1-2 texts by now; on the other hand, do we want to follow the WALS sample strictly?

Please let me know what you think.

**Comment by ximenina** [comment]
I'm closing this issue since the [technical crawler ](https://github.com/MorphDiv/TeDDi_sample/pull/271) was added recently
