### ISSUE TITLE
Tiwi Grammar by Lee (1987)

### ISSUE THREAD

**Issue by christianbentz** [MorphDiv/TeDDi_sample#219]
Transcribe texts in Lee (1987) Tiwi today, a study of language change in a contact situation. There are texts in the appendix, which should be transcribed.

**Comment by ximenina** [comment]
I think this task was already accomplished in: https://github.com/MorphDiv/TeDDi_sample/tree/master/Corpus/Tiwi_tiw/non-fiction/spoken

So, I'm closing this issue.
