### ISSUE TITLE
Bagirmi Lexicon by Keegan and Djibrine (2016) 

### ISSUE THREAD

**Issue by bambooforest** [MorphDiv/TeDDi_sample#25]
This lexicon contains a short grammatical description in English, with example sentences that can be extracted.

In the Bagirmi-French lexicon there are example sentences in Bagirmi with French translations that can also be extracted (the genre is then also example sentences, i.e. gre)

**Comment by ximenina** [comment]
This was addressed already in [Corpus/Bagirmi_bmi/grammar/spoken/Bagirmi_bmi](https://github.com/MorphDiv/TeDDi_sample/blob/master/Corpus/Bagirmi_bmi/grammar/spoken/bmi_gre_1.txt)
