### ISSUE TITLE
Kayardild annotation tiers

### ISSUE THREAD

**Issue by tsamardzic** [MorphDiv/TeDDi_sample#252]
Why is

>  \<line_16>	Ngij-in-thabuju-karra maku-.
>  \<phonological>	ŋicu-iɲ-t̪apucu-kara maku-a
>  \<segmentation>	1sg-fINY-e.Br-fGEN.T wife-T

but

>   \<line_3>	Nga-da dathin-ki-na- wuu-j-arra- wuruman-ki-na- nguku-rnurru--na-
>   \<segmentation>	ŋat̪-ta ʈat̪in-ki-naa-ø wuː-c-ŋara-ø wuɻuman-ki-naa-ø ŋuku-ɳuru-ki-naa-ø
>   \<morphomic>	1sg-T there-fLOC-fABL-T put-TH-fCONS-T billy-fLOC-fABL-T water-fASSOC-fLOC-fABL-T

?

I did everything like \<line 3>.

**Comment by ximenina** [comment]
I think all these remarks were already integrated in https://github.com/MorphDiv/TeDDi_sample/blob/master/Corpus/Kayardild_gyd/grammar/spoken/gyd_gre_1.txt . I'm closing this issue.
