### ISSUE TITLE
Duplicates in OPUS subtitles

### ISSUE THREAD

**Issue by bambooforest** [MorphDiv/TeDDi_sample#34]
@avonizos commented on Aug 2, 2019

TODO:
Find out a way for automatic duplicates identification, their deletion and renaming of the files.

**Comment by ximenina** [comment]
Hi @olgapelloni, I'm currently checking all the TeDDi's open issues.  
Quick question, do you remember if this is still a pending issue? Since I didn't find info about deleting duplicates in your TeDDi: Crawling issues report. Thanks

**Comment by olgapelloni** [comment]
Hi @ximenina,

This was implemented, see the comment in the header of this script: https://github.com/MorphDiv/TeDDi_sample/blob/master/Crawlers/opus_opensubtitles_crawler.py

There is a function check_duplicates in lines 237-264, which is invoked in line 144; I'm not sure though if the running numbers are actually renamed, I might've used some bash command for that. Please check this better.

**Comment by ximenina** [comment]
I'm closing this issue now.
